version: "3.9"

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd1234
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - "3306:3306"

  base_app:
    build:
      context: ./base
    restart: always
    ports:
      - "5005:5000"
    links:
      - "predict_app:predict"
      - "registry_app:register"

  predict_app:
    build:
      context: ./predict
    restart: always
#    ports:
#      - "5001:5001"

  registry_app:
    build:
      context: ./registry
    restart: always
    depends_on:
      - mariadb
#    ports:
#      - "5002:5002"
    links:
      - "mariadb:database"